# Dataset
IMAGE_DATASET_PATH: ""
MASK_DATASET_PATH: ""
TEST_SPLIT: 0.2

# Model
INPUT_IMAGE_WIDTH: 256
INPUT_IMAGE_HEIGHT: 256
NUM_CHANNELS: 3
NUM_CLASSES: 1

# Training
INIT_LR: 0.001
NUM_EPOCHS: 50
BATCH_SIZE: 8
EARLY_STOPPING_PATIENCE: 10
REDUCE_LR_PATIENCE: 4
REDUCE_LR_FACTOR: 0.2
MIN_LR: 0.000001

# Augmentation
ROTATION_RANGE: 30
WIDTH_SHIFT_RANGE: 0.2
HEIGHT_SHIFT_RANGE: 0.2
SHEAR_RANGE: 0.15
ZOOM_RANGE: 0.2
HORIZONTAL_FLIP: true
VERTICAL_FLIP: false
BRIGHTNESS_RANGE: [0.8, 1.2]
fill_mode: 'reflect'

# Output
BASE_OUTPUT: "./results"
MODEL_PATH: "./results/models/unet_model.keras"
PLOT_PATH: "./results/figures/predictions.png"
HISTORY_PLOT_PATH: "./results/figures/training_history.png"